# Generated by Django 2.2.12 on 2020-09-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chocie_text',
            new_name='choice_text',
        ),
    ]
